- name: RandomResizedCrop
  params:
    size: ${data.img_size}
    scale: [0.08, 0.4]
- name: RandomHorizontalFlip
  params: {}
- name: ColorJitter
  params:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.2
    hue: 0.1
- name: GaussianBlur
  params:
    kernel_size: 7
    sigma: [0.1, 2.0]
- name: ToTensor