data:
  dataset_name: 'cifar10'
  data_csv: 'training_data/cifar10/trainLabels.csv'
  data_dir: 'training_data/cifar10/train'
  val_split: 0.2
  num_workers: 4
  img_size: 112

model:
  patch_size: 16
  num_classes: 10 
  in_channels: 3 
  embed_dim: 384
  num_blocks: 3
  num_heads: 6
  mlp_dim: 1536
  dropout: 0.1

training:
  type: 'supervised'
  random_seed: 42
  batch_size: 256
  num_epochs: 100
  warmup_initial_learning_rate: 1e-7
  warmup_final_learning_rate: 1e-3
  warmup_epochs: 10
  lr_final: 1e-6
  weight_decay: 0.001
  checkpoint_dir: './checkpoints'
  criterion:
    name: L1Loss
    params:
      reduction: mean
  optimizer:
    name: AdamW
    params:
      lr: ${training.warmup_initial_learning_rate}
      weight_decay: 0.05
  lr_scheduler:
    main:
      name: CosineAnnealingLR
      params:
        eta_min: 1e-6
    warmup:
      name: LinearWarmupScheduler
      params: {}