defaults:
  - config_schema

  - base@data: data
  - base@model: model
  - base@training: training

  - dino@data: data
  - dino@model: model
  - dino@training: training
  - dino@transforms.globals: globals
  - dino@transforms.locals: locals
  - dino@metrics: metrics

hydra:
  run:
    dir: ./experiments/${training.type}/${now:%Y-%m-%d_%H_%M_%S}