defaults:
  - config_schema
  - data: stl10_unsupervised
  - model: vit_small_dino
  - training: dino_training
  - transforms@transforms.globals: globals
  - transforms@transforms.locals: locals
  - metrics: dino_metrics

hydra:
  run:
    dir: ./experiments/${training.type}/${now:%Y-%m-%d_%H_%M_%S}