data:
  dataset_name: 'stl10'
  data_dir: 'training_data/stl10/unlabeled_images'
  val_split: 0.2
  num_workers: 4
  img_size: 192

model:
  patch_size: 16
  in_channels: 3 
  embed_dim: 384
  num_blocks: 6
  num_heads: 6
  mlp_dim: 1536
  dropout: 0.1
  mask_ratio: 0.5

training:
  type: 'unsupervised'
  random_seed: 42
  batch_size: 128
  num_epochs: 150
  warmup_initial_learning_rate: 1e-7
  warmup_final_learning_rate: 1e-4
  warmup_epochs: 10
  lr_final: 1e-6
  weight_decay: 0.001
  checkpoint_dir: './checkpoints'