experiment_path: 'experiments/supervised/2025-06-19_08_33_14'
confusion_matrix: true

dataset_name: 'stl10'
data_csv: 'training_data/stl10/train_labels.json'
data_dir: 'training_data/stl10/train_images'
num_classes: 10